"""
Alert Model
============
Stores anomaly alerts with severity, threat type, actions, and user response status.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import String, DateTime, Text, Integer, Float, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column

from .database import Base


class Alert(Base):
    """An anomaly alert generated by the detection engine."""

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    anomaly_id: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    device_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("devices.id"), index=True
    )

    # Anomaly details
    severity: Mapped[int] = mapped_column(Integer)           # 1-10
    threat_type: Mapped[str] = mapped_column(String(32))
    # Types: USER_DRIFT, DEVICE_MISUSE, MALWARE_MIMICRY, INSIDER_THREAT
    message: Mapped[str] = mapped_column(Text)
    confidence: Mapped[float] = mapped_column(Float)         # 0.0 - 1.0
    mahalanobis_distance: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True
    )

    # Recommended actions (JSON list)
    actions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # e.g. '["kill_process", "block_network"]'

    # User response
    status: Mapped[str] = mapped_column(String(16), default="pending")
    # Values: pending, approved, denied, snoozed, auto_escalated
    responded_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime, nullable=True
    )

    # Action execution
    action_executed: Mapped[bool] = mapped_column(default=False)
    action_result: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, index=True
    )

    def __repr__(self) -> str:
        return (
            f"<Alert id={self.anomaly_id!r} device={self.device_id!r} "
            f"severity={self.severity} type={self.threat_type!r} "
            f"status={self.status!r}>"
        )
